#!/bin/sh

set -o errexit
set -o nounset

if [ "$1" = "gunicorn" ]; then
  # run migrations and collect static only when app is starting
  python manage.py migrate --noinput
  python manage.py collectstatic --noinput
fi

exec "$@"
