# Generated by Django 5.1.2 on 2024-10-27 22:11

import model_utils.fields
import proxies.proxies.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=proxies.proxies.models.default_proxy_name, max_length=64, unique=True)),
                ('provider', models.CharField(choices=[('digitalocean', 'DigitalOcean'), ('hetzner', 'Hetzner')], default='digitalocean', max_length=32)),
                ('server_id', models.PositiveIntegerField(null=True)),
                ('ipaddress', models.GenericIPAddressField(null=True, protocol='ipv4')),
                ('active', models.BooleanField(default=False)),
                ('create_request_at', models.DateTimeField(null=True)),
                ('create_response', models.JSONField(null=True)),
                ('last_check_at', models.DateTimeField(null=True)),
                ('last_check_response', models.JSONField(null=True)),
                ('reported', models.BooleanField(default=False, editable=False)),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'proxy',
                'verbose_name_plural': 'proxies',
                'ordering': ['name'],
            },
        ),
    ]
