# Generated by Django 5.1.2 on 2024-10-27 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_proxy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_clients', to='proxies.proxy'),
        ),
    ]
