# Generated by Django 5.1.2 on 2024-10-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0003_client_default_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
