# Generated by Django 5.1.2 on 2024-10-27 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0004_proxy_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='default_proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_clients', to='proxies.proxy'),
        ),
    ]
